name: Test Build and Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  unitary_test:
    name: Unitary Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Run Unitary Tests
        env:
          CI: true
        run: npm test
integration_test:
    name: E2E Tests
    needs: unitary_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Run E2E Tests
        env:
          CI: true
        run: npm run test:e2e
  deploy:
    name: Deploy to Heroku
    needs: integration_test
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Set heroku remote
        run: heroku git:remote -a nest-test-backend
      - name: push code to heroku
        run: git push heroku master
     