name: Test Build and Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Set heroku remote
        run: heroku git:remote -a nest-test-backend 
      - name: push code to heroku
        run: git push heroku master
     