name: Test Build and Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Unitary Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        env:
          CI: true
        run: npm test
  build:
    name: Build Nest App
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run postinstall
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nest-test-backend"
          heroku_email: "diego.netsolutions@gmail.com"
          procfile: "web: npm run start:prod"
          appdir: "dist"