name: Test Build and Deploy to Heroku
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Unitary and E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Run Unitary Tests
        env:
          CI: true
        run: npm test
      - name: Run E2E Tests
        env:
          CI: true
        run: npm run test:e2e
  build:
    name: Build Nest App
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run postinstall
      - name: Add Proper Procfile
        run: npm run copy-procfile
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: test heroku login
        run: heroku apps
      - name: list
        run: ls -a
      - name: cd
        run: cd dist
      - name: git status
        run: git status
